apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wjca
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-wjca@sha256:a52fd95d0f0100255834a5104bd06b7236260d889d8ee7dc1f6d7551f76a945d
        name: my-nodejs
        resources: {}
status: {}
